// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package mydata

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (Metrics) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Metrics) UnmarshalJSON([]byte) error        { return nil }
func (Metrics) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Metrics) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Metrics *Metrics
